<?php

/**
 * @file
 * Provides Frontend features.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_template_preprocess_default_variables_alter().
 */
function digital_store_frontend_template_preprocess_default_variables_alter(&$variables) {
  $frontend_helper = \Drupal::service('digital_store_frontend.helper');
  $variables['is_mobile'] = $frontend_helper->isMobile();
  $variables['is_tablet'] = $frontend_helper->isTablet();
  $variables['is_desktop'] = $frontend_helper->isDesktop();
}

/**
 * Implements hook_ENTITY_TYPE_build_defaults_alter().
 */
function digital_store_frontend_node_build_defaults_alter(array &$build, EntityInterface $entity, $view_mode) {
  if (!($entity instanceof NodeInterface)) {
    return;
  }
  $bundle = $entity->bundle();
  $suitable = ($bundle == 'landing_page') || (strpos($bundle, 'widget_') !== FALSE);
  if (!$suitable) {
    return;
  }
  // Add Device Cache context to vary node output based on device screen sizes.
  $build['#cache']['contexts'][] = 'device';
}