# Schema for the Stripe Settings.
digital_store.settings.stripe:
  type: config_object
  label: 'Stripe Settings'
  mapping:
    stripe_api_endpoint:
      type: string
      label: 'Stripe API Endpoint'
    publishable_key:
      type: string
      label: 'Publishable key'
    secret_key:
      type: string
      label: 'Secret key'
    connection_environment:
      type: string
      label: 'Whether Stripe API is currently in test mode'
    capture:
      type: boolean
      label: 'Transaction mode: Authorize and capture or Authorize only'