title: 'Subscription options'
description: '<p>A subscription entitles you to <a target="_blank" href="/support-policy/"><strong>1 year of updates and support</strong></a> from the date of purchase. Each installation of the plugin will require a license key.</p>'
quick_buy: true
